name: eminfo_env
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9.12
  - pip=23.0.1
  - pytorch=2.0.0=py3.9_cuda11.7_cudnn8.5.0_0
  - torchaudio=2.0.0=py39_cu117
  - torchvision=0.15.0=py39_cu117
  - pip:
    - biopython==1.79
    - joblib==1.2.0
    - mrcfile==1.3.0
    - numpy==1.24.2
    - scikit-learn==1.1.1
    - scipy==1.10.1
    - threadpoolctl==3.1.0
